/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-06-26 10:08:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class feedback_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Feedback | Telusko</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.css\"/>\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    @import url('https://fonts.googleapis.com/css?family=Comfortaa');\r\n");
      out.write("      body {\r\n");
      out.write("        background-color: rgba(231, 238, 243, 0.72);\r\n");
      out.write("        padding-top: 50px; \r\n");
      out.write("      }\r\n");
      out.write("      /* Simple Navbar Design */\r\n");
      out.write("      .navbar {\r\n");
      out.write("        margin-bottom: 50px;\r\n");
      out.write("        border-radius: 0px;\r\n");
      out.write("        background: #2c3e50;\r\n");
      out.write("        border: none;\r\n");
      out.write("      }\r\n");
      out.write("      .navbar .active>a, .navbar-default .navbar-nav>.active>a:hover, .navbar-default .navbar-nav>.active>a:focus {\r\n");
      out.write("        color: #e7e7e7;\r\n");
      out.write("        background: rgba(56, 98, 144, 0.78);\r\n");
      out.write("      }\r\n");
      out.write("      .btn, .btn-large {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color: #51b42a;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    letter-spacing: .5px;\r\n");
      out.write("    transition: .2s ease-out;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("input:not([type]):focus:not([readonly]),\r\n");
      out.write("input[type=text]:focus:not([readonly]),\r\n");
      out.write("input[type=password]:focus:not([readonly]),\r\n");
      out.write("input[type=email]:focus:not([readonly]),\r\n");
      out.write("input[type=url]:focus:not([readonly]),\r\n");
      out.write("input[type=time]:focus:not([readonly]),\r\n");
      out.write("input[type=date]:focus:not([readonly]),\r\n");
      out.write("input[type=datetime]:focus:not([readonly]),\r\n");
      out.write("input[type=datetime-local]:focus:not([readonly]),\r\n");
      out.write("input[type=tel]:focus:not([readonly]),\r\n");
      out.write("input[type=number]:focus:not([readonly]),\r\n");
      out.write("input[type=search]:focus:not([readonly]),\r\n");
      out.write("textarea.materialize-textarea:focus:not([readonly]) {\r\n");
      out.write("  border-bottom: 1px solid #51b42a;\r\n");
      out.write("  box-shadow: 0 1px 0 0 #51b42a;\r\n");
      out.write("}\r\n");
      out.write("input:not([type]):focus:not([readonly]) + label,\r\n");
      out.write("input[type=text]:focus:not([readonly]) + label,\r\n");
      out.write("input[type=password]:focus:not([readonly]) + label,\r\n");
      out.write("input[type=email]:focus:not([readonly]) + label,\r\n");
      out.write("input[type=url]:focus:not([readonly]) + label,\r\n");
      out.write("input[type=time]:focus:not([readonly]) + label,\r\n");
      out.write("input[type=date]:focus:not([readonly]) + label,\r\n");
      out.write("input[type=datetime]:focus:not([readonly]) + label,\r\n");
      out.write("input[type=datetime-local]:focus:not([readonly]) + label,\r\n");
      out.write("input[type=tel]:focus:not([readonly]) + label,\r\n");
      out.write("input[type=number]:focus:not([readonly]) + label,\r\n");
      out.write("input[type=search]:focus:not([readonly]) + label,\r\n");
      out.write("textarea.materialize-textarea:focus:not([readonly]) + label {\r\n");
      out.write("  color: #51b42a;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-content li > a, .dropdown-content li > span {\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #51b42a;\r\n");
      out.write("    display: block;\r\n");
      out.write("    line-height: 22px;\r\n");
      out.write("    padding: 14px 16px;\r\n");
      out.write("}\r\n");
      out.write("button:focus {\r\n");
      out.write("    outline: none;\r\n");
      out.write("    background-color: #51b42a;\r\n");
      out.write("}\r\n");
      out.write(".btn:hover, .btn-large:hover {\r\n");
      out.write("  background-color: #51b42a;\r\n");
      out.write("}\r\n");
      out.write("div.error {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    top: -1rem;\r\n");
      out.write("    left: 0rem;\r\n");
      out.write("    font-size: 0.8rem;\r\n");
      out.write("    color: #FF4081;\r\n");
      out.write("    -webkit-transform: translateY(0%);\r\n");
      out.write("    -ms-transform: translateY(0%);\r\n");
      out.write("    -o-transform: translateY(0%);\r\n");
      out.write("    transform: translateY(0%);\r\n");
      out.write("}\r\n");
      out.write("      /* Feedback Form Styles */\r\n");
      out.write("      form p {\r\n");
      out.write("        font-size: 120%;\r\n");
      out.write("      }\r\n");
      out.write("      form .row {\r\n");
      out.write("      \tmargin-bottom: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      .ctrlqHeaderMast {\r\n");
      out.write("        height: 140px;\r\n");
      out.write("        /*background: rgba(36, 194, 255, 0.87);*/\r\n");
      out.write("      }\r\n");
      out.write("      .header{\r\n");
      out.write("        /*background-color: green;*/\r\n");
      out.write("        font-family: 'Comfortaa', cursive;\r\n");
      out.write("      }\r\n");
      out.write("      .ctrlqFormContent {\r\n");
      out.write("        color: rgba(0,0,0,.87);\r\n");
      out.write("        padding: 20px 35px\r\n");
      out.write("      }\r\n");
      out.write("      .ctrlqFormContentWrapper {\r\n");
      out.write("        display: -webkit-box;\r\n");
      out.write("        display: -moz-box;\r\n");
      out.write("        display: -webkit-flex;\r\n");
      out.write("        display: -ms-flexbox;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        -webkit-box-orient: vertical;\r\n");
      out.write("        box-orient: vertical;\r\n");
      out.write("        -webkit-flex-direction: column;\r\n");
      out.write("        flex-direction: column\r\n");
      out.write("      }\r\n");
      out.write("      .ctrlqAccent {\r\n");
      out.write("        background-color: #51b42a;\r\n");
      out.write("        height: 8px;\r\n");
      out.write("      }\r\n");
      out.write("      .ctrlqCenteredContent {\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        width: 70%; \r\n");
      out.write("      }\r\n");
      out.write("      .ctrlqFormCard {\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        margin-bottom: 48px;\r\n");
      out.write("        -webkit-box-shadow: 0 1px 4px 0 rgba(0,0,0,0.37);\r\n");
      out.write("        box-shadow: 0 1px 4px 0 rgba(0,0,0,0.37);\r\n");
      out.write("        word-wrap: break-word\r\n");
      out.write("      }\r\n");
      out.write("      .ctrlqFormCard:first-of-type {\r\n");
      out.write("        margin-top: -100px\r\n");
      out.write("      }\r\n");
      out.write("      .ctrlqHeaderTitle {\r\n");
      out.write("        -webkit-box-sizing: border-box;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        font-size: 34px;\r\n");
      out.write("        line-height: 135%;\r\n");
      out.write("        max-width: 100%;\r\n");
      out.write("        min-width: 0%;\r\n");
      out.write("        margin-bottom: 22px\r\n");
      out.write("      }\r\n");
      out.write("      @media (max-width: 660px) {\r\n");
      out.write("        .ctrlqHeaderMast {\r\n");
      out.write("          height: 122px;\r\n");
      out.write("        }\r\n");
      out.write("        .ctrlqFormCard:first-of-type {\r\n");
      out.write("          margin-top: -50px;\r\n");
      out.write("        }\r\n");
      out.write("        .ctrlqCenteredContent {\r\n");
      out.write("          width: 92%;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("      div.error {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        top: -1rem;\r\n");
      out.write("        left: 0rem;\r\n");
      out.write("        font-size: 0.8rem;\r\n");
      out.write("        color: #FF4081;\r\n");
      out.write("        -webkit-transform: translateY(0%);\r\n");
      out.write("        -ms-transform: translateY(0%);\r\n");
      out.write("        -o-transform: translateY(0%);\r\n");
      out.write("        transform: translateY(0%);\r\n");
      out.write("      }\r\n");
      out.write("      /* Rating Star Styles */\r\n");
      out.write("      [type=\"radio\"]+label:before, [type=\"radio\"]+label:after {\r\n");
      out.write("        top:auto;\r\n");
      out.write("        left: auto;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        width: auto;\r\n");
      out.write("        height: auto;\r\n");
      out.write("      }\r\n");
      out.write("      [type=\"radio\"]:not(:checked)+label, [type=\"radio\"]:checked+label {\r\n");
      out.write("        padding-left: 0px;\r\n");
      out.write("      }\r\n");
      out.write("      .row p {\r\n");
      out.write("        margin-left: 15px;\r\n");
      out.write("        font-size: 15px;\r\n");
      out.write("        color: #9e9e9e;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("      }\r\n");
      out.write("      .overallRatings {\r\n");
      out.write("        font-size: 0;\r\n");
      out.write("        unicode-bidi: bidi-override;\r\n");
      out.write("        direction: rtl;\r\n");
      out.write("      }\r\n");
      out.write("      .ratings {\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("        font-family:  'Comfortaa', cursive;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        font-size: 17px;\r\n");
      out.write("        color:rgb(74, 71, 71); \r\n");
      out.write("      }\r\n");
      out.write("      .overallRatings {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        top:0px;\r\n");
      out.write("        left: 15px;\r\n");
      out.write("      }\r\n");
      out.write("      .overallRatings label {\r\n");
      out.write("        font-size: 30px !important;\r\n");
      out.write("      }\r\n");
      out.write("      .overallRatings .error {\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        padding-top: 15px;\r\n");
      out.write("      }\r\n");
      out.write("      .overallRatings > input {\r\n");
      out.write("        display: none;\r\n");
      out.write("      }\r\n");
      out.write("      .overallRatings > input + label {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        text-indent: 9999px;\r\n");
      out.write("        width: 1em;\r\n");
      out.write("        white-space: nowrap;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        font-size: 35px;\r\n");
      out.write("      }\r\n");
      out.write("      .overallRatings > input + label:before {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        text-indent: -9999px;\r\n");
      out.write("        content: \"â\";\r\n");
      out.write("        color: #888;\r\n");
      out.write("      }\r\n");
      out.write("      .overallRatings > input:checked ~ label:before, .overallRatings > input + label:hover ~ label:before, .overallRatings > input + label:hover:before {\r\n");
      out.write("        content: \"â\";\r\n");
      out.write("        color: #ffeb3b;\r\n");
      out.write("        text-shadow: 0 0 1px #333;\r\n");
      out.write("      }\r\n");
      out.write("      .overallRatings > .star-cb-clear + label {\r\n");
      out.write("        text-indent: -9999px;\r\n");
      out.write("        width: .5em;\r\n");
      out.write("        margin-left: -.5em;\r\n");
      out.write("      }\r\n");
      out.write("      .overallRatings > .star-cb-clear + label:before {\r\n");
      out.write("        width: .5em;\r\n");
      out.write("      }\r\n");
      out.write("      .overallRatings:hover > input + label:before {\r\n");
      out.write("        content: \"â\";\r\n");
      out.write("        color: #888;\r\n");
      out.write("        text-shadow: none;\r\n");
      out.write("      }\r\n");
      out.write("      .overallRatings:hover > input + label:hover ~ label:before, .overallRatings:hover > input + label:hover:before {\r\n");
      out.write("        content: \"â\";\r\n");
      out.write("        color: #ffeb3b;\r\n");
      out.write("        text-shadow: 0 0 1px #333;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("   <!--  <div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span> \r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"#\">Telusko</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("          <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <li><a href=\"#\">Home</a></li>\r\n");
      out.write("            <li><a href=\"#\">Video</a></li>\r\n");
      out.write("            <li><a href=\"#\">Codes</a></li> \r\n");
      out.write("            <li><a href=\"#\">Test</a></li>\r\n");
      out.write("            <li class=\"active\"><a href=\"#\">Feedback</a></li>\r\n");
      out.write("            <li><a href=\"#\">About us</a></li> \r\n");
      out.write("          </ul>\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li><a href=\"#\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a></li>\r\n");
      out.write("            <li><a href=\"#\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write(" -->\r\n");
      out.write("    <div class=\"ctrlqFormContentWrapper\">\r\n");
      out.write("      <div class=\"ctrlqHeaderMast\"></div>\r\n");
      out.write("      <div class=\"ctrlqCenteredContent\">\r\n");
      out.write("        <div class=\"ctrlqFormCard\">\r\n");
      out.write("          <div class=\"ctrlqAccent\"></div>\r\n");
      out.write("          <div class=\"ctrlqFormContent\">\r\n");
      out.write("\r\n");
      out.write("            <form action=\"addFeedback\" method=\"get\">  \r\n");
      out.write("\r\n");
      out.write("              <div class=\"row header\">\r\n");
      out.write("                <div class=\"input-field col s12 navbar-collapse\" align=\"center\">\r\n");
      out.write("                  <h4 style=\"font-weight: bolder;\">Feedback Us</h4>\r\n");
      out.write("                  <p><center>Your Feedback Matters</center> </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"input-field col s12\">\r\n");
      out.write("                  <input id=\"name\" name=\"name\" pattern=\"[A-Za-z]{2,}\" title=\"Two or more characters\" type=\"text\" class=\"validate\" data-error=\"#e1\" required>\r\n");
      out.write("                  <label for=\"name\">Your Name</label>\r\n");
      out.write("                  <div id=\"e1\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"input-field col s12\">\r\n");
      out.write("                  <input id=\"email\" name=\"email\" pattern=\"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,3}$\" title=\"Invalid Email Address\" type=\"text\" class=\"validate\" data-error=\"#e2\" required>\r\n");
      out.write("                  <label for=\"email\">Your Email</label>\r\n");
      out.write("                  <div id=\"e2\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"input-field col s12\">\r\n");
      out.write("                 <!--  <select id=\"reg\" name=\"reg\" class=\"validate\" data-error=\"#e3\" required>    \r\n");
      out.write("                      <option value=\"1\">Website</option> \r\n");
      out.write("                      <option value=\"2\">Mr. Navin Reddy</option>\r\n");
      out.write("                      <option value=\"3\">Online Course</option>\r\n");
      out.write("                  </select> -->\r\n");
      out.write("                  \r\n");
      out.write("                   <input id=\"reg\" name=\"reg\" title=\"Two or more characters\" type=\"text\" class=\"validate\" data-error=\"#e1\" required>\r\n");
      out.write("                  <label for=\"name\">Regarding</label>\r\n");
      out.write("                  \r\n");
      out.write("                  <div id=\"e3\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("                <div class=\"input-field col s12\">\r\n");
      out.write("                  <input id=\"code\" name=\"code\" type=\"text\" class=\"validate\" data-error=\"#e5\">\r\n");
      out.write("                  <label for=\"code\">Code(If any)</label>\r\n");
      out.write("                  <div id=\"e5\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"input-field col s12\">\r\n");
      out.write("                  <textarea pattern=\".{1,}\" title=\"One or more characters\" id=\"msg\" name=\"msg\" class=\"materialize-textarea\" data-error=\"#e4\" required></textarea>\r\n");
      out.write("                  <label for=\"msg\">Feedback Message</label>\r\n");
      out.write("                  <div id=\"e4\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <p>Overall Rating</p>\r\n");
      out.write("                <span class=\"overallRatings\">\r\n");
      out.write("                  <input type=\"radio\" name=\"rating\" style=\"display:none\" required/>\r\n");
      out.write("                  <div style=\"clear:both;\"></div>\r\n");
      out.write("                  <input type=\"radio\" id=\"rating-5\" name=\"rating\" value=\"5\"/><label for=\"rating-5\"></label>\r\n");
      out.write("                  <input type=\"radio\" id=\"rating-4\" name=\"rating\" value=\"4\" /><label for=\"rating-4\"></label>\r\n");
      out.write("                  <input type=\"radio\" id=\"rating-3\" name=\"rating\" value=\"3\" /><label for=\"rating-3\"></label>\r\n");
      out.write("                  <input type=\"radio\" id=\"rating-2\" name=\"rating\" value=\"2\" /><label for=\"rating-2\"></label>\r\n");
      out.write("                  <input type=\"radio\" id=\"rating-1\" name=\"rating\" value=\"1\"/><label for=\"rating-1\"></label>\r\n");
      out.write("                </span>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"input-field col m6 s12\">\r\n");
      out.write("                  <button type=\"reset\" value=\"reset\" class=\"waves-effect waves-light btn-large navbar-right\">Reset</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-field col m6 s12\">\r\n");
      out.write("                  <button type=\"submit\" class=\"waves-effect waves-light btn-large\">Submit</button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.0/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.0/additional-methods.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      $(document).ready(function() {\r\n");
      out.write("        $('[type*=\"radio\"]').change(function () {\r\n");
      out.write("          var me = $(this);\r\n");
      out.write("        });\r\n");
      out.write("        $('select').material_select();\r\n");
      out.write("        $.validator.setDefaults({\r\n");
      out.write("          ignore: []\r\n");
      out.write("        });\r\n");
      out.write("        $(\"form\").validate({\r\n");
      out.write("          submitHandler: function(form) {\r\n");
      out.write("            alert(\"Thank you for Feedback\");\r\n");
      out.write("            return true;\r\n");
      out.write("            \r\n");
      out.write("          },\r\n");
      out.write("          errorElement: 'div',\r\n");
      out.write("          errorPlacement: function(error, element) {\r\n");
      out.write("            var placement = $(element).data('error');\r\n");
      out.write("            if (placement) {\r\n");
      out.write("              $(placement).append(error)\r\n");
      out.write("            } else {\r\n");
      out.write("              error.insertAfter(element);\r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("  </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
